 # Find all the available rules by running:
 # swiftlint rules

disabled_rules:
- trailing_whitespace

excluded:
- ${PWD}/Build
- ${PWD}/DerivedData
- ${PWD}/.git

# some rules are only opt-in
opt_in_rules:
 - accessibility_trait_for_button
 - discouraged_assert
 #- anyobject_protocol
 - balanced_xctest_lifecycle
 - contains_over_filter_count
 - contains_over_filter_is_empty
 - contains_over_range_nil_comparison
 - empty_collection_literal
 - enum_case_associated_values_count
 - file_types_order
 - legacy_multiple
 #- nslocalizedstring_require_bundle
 - reduce_into
 - type_contents_order
 - unowned_variable_capture
 #- array_init
 - attributes
 - closure_body_length
 - closure_end_indentation
 - closure_spacing
 - collection_alignment
 #- conditional_returns_on_newline
 #- contains_over_first_not_nil
 - convenience_type
 #-discouraged_object_literal
 - discouraged_optional_boolean
 - discouraged_optional_collection
 - direct_return
 - empty_count
 - empty_string
 - empty_xctest_method
 #- explicit_acl
 #- explicit_enum_raw_value
 - expiring_todo
 - explicit_init
 #- explicit_top_level_acl
 #- explicit_type_interface
 - extension_access_modifier
 - fallthrough
 - fatal_error_message
 #- file_header
 - file_name
 - file_name_no_space
 - first_where
 - flatmap_over_map_reduce
 - force_unwrapping
 - function_default_parameter_at_end
 - identical_operands
 #- ibinspectable_in_extension
 #- implicit_return
 - implicitly_unwrapped_optional
 - joined_default_parameter
 - last_where
 #- legacy_objc_type
 - legacy_random
 #- let_var_whitespace
 - literal_expression_end_indentation
 - lower_acl_than_parent
 - modifier_order
 - multiline_arguments
 - multiline_function_chains
 - multiline_parameters
 - nimble_operator
 #- no_extension_access_modifier
 #- no_grouping_extension
 #- number_separator
 - object_literal
 - optional_enum_case_matching
 - operator_usage_whitespace
 - orphaned_doc_comment
 - overridden_super_call
 - override_in_extension
 - pattern_matching_keywords
 - prefer_self_type_over_type_of_self
 - prefer_zero_over_explicit_init
 - prefixed_toplevel_constant
 - private_action
 - private_outlet
 - private_subject
 - prohibited_super_call
 - quick_discouraged_call
 - quick_discouraged_focused_test
 - quick_discouraged_pending_test
 - raw_value_for_camel_cased_codable_enum
 - redundant_nil_coalescing
 - required_enum_case
 - return_value_from_void_function
 - single_test_class
 #- sorted_first_last
 - sorted_imports
 #- strict_fileprivate
 - switch_case_on_newline
 - toggle_bool
 - trailing_closure
 - unavailable_function
 #- unneeded_notification_center_removal
 - unneeded_parentheses_in_closure_argument
 - untyped_error_in_catch
 #- vertical_parameter_alignment_on_call
 #- yoda_condition
 #- inert_defer
 - local_doc_comment
 - period_spacing
 - shorthand_optional_binding
